// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0c49-WNb8SVevawTGBCHkhoFAbWEQeiI',
    appId: '1:549239369856:web:88b8834a6339ca25a67665',
    messagingSenderId: '549239369856',
    projectId: 'siwpe-me',
    authDomain: 'siwpe-me.firebaseapp.com',
    storageBucket: 'siwpe-me.appspot.com',
    measurementId: 'G-WM1YSRWGB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rcWJ5ymwTCEtoKRh0BkTxcRlMrNLD7c',
    appId: '1:549239369856:android:c2abe70cf5c74bfca67665',
    messagingSenderId: '549239369856',
    projectId: 'siwpe-me',
    storageBucket: 'siwpe-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLJLhGHXcLd6_jLbbCnvPpN740QnXjk3Q',
    appId: '1:549239369856:ios:0a20c27db1a0b922a67665',
    messagingSenderId: '549239369856',
    projectId: 'siwpe-me',
    storageBucket: 'siwpe-me.appspot.com',
    iosClientId: '549239369856-f5rc0mllej1j1197pbrfcrilnqanachu.apps.googleusercontent.com',
    iosBundleId: 'com.example.swipeMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLJLhGHXcLd6_jLbbCnvPpN740QnXjk3Q',
    appId: '1:549239369856:ios:0a20c27db1a0b922a67665',
    messagingSenderId: '549239369856',
    projectId: 'siwpe-me',
    storageBucket: 'siwpe-me.appspot.com',
    iosClientId: '549239369856-f5rc0mllej1j1197pbrfcrilnqanachu.apps.googleusercontent.com',
    iosBundleId: 'com.example.swipeMe',
  );
}
